// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurvivorWebApi.Data;

#nullable disable

namespace SurvivorWebApi.Migrations
{
    [DbContext(typeof(SurvivorDbContext))]
    [Migration("20241007114608_AddingSampleData")]
    partial class AddingSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurvivorWebApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 7, 14, 46, 7, 648, DateTimeKind.Local).AddTicks(7677),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 7, 14, 46, 7, 648, DateTimeKind.Local).AddTicks(7687),
                            Name = "Celebrities"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 7, 14, 46, 7, 648, DateTimeKind.Local).AddTicks(7693),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 7, 14, 46, 7, 648, DateTimeKind.Local).AddTicks(7693),
                            Name = "Volunteers"
                        });
                });

            modelBuilder.Entity("SurvivorWebApi.Entities.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 7, 14, 46, 7, 648, DateTimeKind.Local).AddTicks(7800),
                            FirstName = "Mert",
                            IsDeleted = false,
                            LastName = "Topcu",
                            ModifiedDate = new DateTime(2024, 10, 7, 14, 46, 7, 648, DateTimeKind.Local).AddTicks(7800)
                        });
                });

            modelBuilder.Entity("SurvivorWebApi.Entities.Competitor", b =>
                {
                    b.HasOne("SurvivorWebApi.Entities.Category", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SurvivorWebApi.Entities.Category", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
